# 'arrtBuild' pipeline for validating PRs before they get merged.
# Unrelated to the release process.

pr:
- main

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
  - repository: ArrtDependencies
    type: git
    name: "Mixed Reality Services/arr.arrt.dependencies"
    endpoint: ArrtCiConnection
    ref: main
    
steps:
- checkout: ArrtDependencies
  lfs: true
  fetchDepth: 1
- checkout: self
  submodules: true
  fetchDepth: 1

- task: PowerShell@2
  displayName: Generate Solution for vs2019
  inputs:
    targetType: inline
    script: |
      $Env:Path = "$(Build.SourcesDirectory)\arr.arrt.dependencies\CMake\bin;$Env:Path"
      $(Build.SourcesDirectory)\azure-remote-rendering-asset-tool\GenerateSolution.ps1 -Destination $(Build.SourcesDirectory)\ArrtWorkspace -Vcpkg "$(Build.SourcesDirectory)\arr.arrt.dependencies\vcpkg"

- task: ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@2
  displayName: 'CredScan'
  condition: always()
  inputs:
    toolMajorVersion: 'V2'
    scanFolder: '$(Build.SourcesDirectory)\azure-remote-rendering-asset-tool\'

- task: VSBuild@1
  inputs:
    solution: '$(Build.SourcesDirectory)\ArrtWorkspace\Arrt.sln'
    platform: 'x64'
    configuration: 'Release'
    msbuildArchitecture: 'x64'
