# buddy pipeline triggered on PR to main, to build ARRT and check for errors
# unrelated to the release process

pr:
- main

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
  - repository: ArrtDependencies
    type: git
    name: "Mixed Reality Services/arr.arrt.dependencies"
    endpoint: ArrtCiConnection
    ref: main
    
steps:
- checkout: ArrtDependencies
  lfs: true
- checkout: self
  submodules: true

- task: BatchScript@1
  displayName: 'Generate solution for vs2019' 
  inputs:
    filename: '$(Build.SourcesDirectory)\arr.arrt.dependencies\GenerateSolution.bat'
    arguments: '-vs2019'
    workingFolder: 'arr.arrt.dependencies'

- task: ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@2
  displayName: 'CredScan'
  condition: always()
  inputs:
    toolMajorVersion: 'V2'
    scanFolder: '$(Build.SourcesDirectory)\azure-remote-rendering-asset-tool\'

- task: VSBuild@1
  inputs:
    solution: '$(Build.SourcesDirectory)\ArrtWorkspace\Arrt.sln'
    platform: 'x64'
    configuration: 'Release'
    msbuildArchitecture: 'x64'
