# pipeline triggered on PR to master, to build ARRT and check for errors

pr:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC'

resources:
  repositories:
  - repository: ArrtDependencies
    type: git
    name: "Mixed Reality Services/arr.arrt.dependencies"
    endpoint: ArrtCiConnection

    
steps:
- checkout: ArrtDependencies
  lfs: true
- checkout: self

- task: BatchScript@1
  displayName: 'Generate solution for vs2017' 
  inputs:
    filename: '$(Build.SourcesDirectory)\arr.arrt.dependencies\GenerateSolution.bat'
    arguments: '-vs2017'
    workingFolder: 'arr.arrt.dependencies'

- task: PowerShell@2
  displayName: 'Check Clang-format'
  inputs:
    filePath: '$(Build.SourcesDirectory)\azure-remote-rendering-asset-tool\.pipelines\CheckFormatCompliant.ps1'
    arguments: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\vcpackages\"'

- task: ea576cd4-c61f-48f8-97e7-a3cb07b90a6f@2
  displayName: 'CredScan'
  condition: always()
  inputs:
    toolMajorVersion: 'V2'
    scanFolder: '$(Build.SourcesDirectory)\azure-remote-rendering-asset-tool\'

- task: VSBuild@1
  inputs:
    solution: '$(Build.SourcesDirectory)\ArrtWorkspace\Arrt.sln'
    platform: 'x64'
    configuration: 'Release'
    msbuildArchitecture: 'x64'




